# Enable/Disable Built-In Features
aha_board: false
question_board: false

# Custom Sidebar Links to External Sites.
# ----------------------------------------
# Must be an array.  Start with a dash on its own line.
# Then indent and provide label, url, and fa icon (optional)
# The default icon is fa-cloud.
# sidebar:

  
